### ISSUE TITLE
Colores del sistema

### ISSUE THREAD

**Issue by macarro123** [AgustinLorenzo/BugTracker#14]
He notado que a la hora de aplicar estilo en colores del sistema, no lo aplica en su totalidad. Si selecciono claro (con wallpaper oscuro), me lo aplica en la barra de notificaciones pero no en el cajón (sigue adecuándose al color del fondo) y los menús contextuales de los iconos en el home.

**Comment by AgustinLorenzo** [comment]
Revisa en la ultima version, debio de quedar resuelto.
