### ISSUE TITLE
Sugerencia añadir borrado de historial de bateria

### ISSUE THREAD

**Issue by Schvelt** [AgustinLorenzo/BugTracker#2]
Añadir un botón para el borrado del historial de batería antes de su borrado automático cuando se carga la batería por encima del 90%. 

Esta implementado en roms como RR o AEX. 
La foto adjunta es de aosip.
![aosip](https://user-images.githubusercontent.com/38046575/38261722-60a898b8-376b-11e8-8d68-0b1261e2db3d.jpg)

**Comment by AgustinLorenzo** [comment]
Cerramos, en la siguiente build esta.

Link: https://github.com/AgustinLorenzo/android_frameworks_base/commit/734d278424ea895e2c44408b79434a96f43eb1cb
Link 2: https://github.com/AgustinLorenzo/android_packages_apps_Settings/commit/7e0344ed1c7d9e0c00d4e8eca33f2f3b0afc1b75
