### ISSUE TITLE
Alto consumo de la app de camara nativa sin mantenerla abierta

### ISSUE THREAD

**Issue by Schvelt** [AgustinLorenzo/BugTracker#3]
Habiendo usado solo una vez la cámara de LOS, abriéndola y cerrándola justo después, al terminar el día tras el primer ciclo de batería, ha dado ese consumo alto. 
Vengo de una instalación limpia. 
![camara los](https://user-images.githubusercontent.com/38046575/38261847-c156e55c-376b-11e8-99ac-4044d969b927.jpg)

La foto esta tomada al terminar de cargar la bateria tras el primer ciclo de carga. 

Se sospecha de que una vez abierto se ha quedado pillada.

**Comment by AgustinLorenzo** [comment]
Cerramos.

En la siguiente build esta reparado

Link: https://github.com/AgustinLorenzo/android_frameworks_av/commit/71697586b061b14630e9e58548bdf79ae9baa084
