### ISSUE TITLE
Sugerencia implementar el thermal del pixel xl 

### ISSUE THREAD

**Issue by Schvelt** [AgustinLorenzo/BugTracker#4]
Implementar el thermal del Pixel xl en las siguientes builds de la rom.

Código:
https://github.com/AOSiP-Devices/device_leeco_msm8996-common/blob/oreo-mr1/configs/thermal-engine.conf

**Comment by AgustinLorenzo** [comment]
Cerramos.

En la siguiente estan: https://github.com/AgustinLorenzo/android_device_zuk_msm8996-common/commit/1d30dbbc9ad51d617b4564196c2d3a4863c66264
