### ISSUE TITLE
Altos consumos de red móvil en espera

### ISSUE THREAD

**Issue by Schvelt** [AgustinLorenzo/BugTracker#6]
Los consumos de la Red móvil de en espera son altos, aunque tengo dos sims puede deberse a algún proceso con los sensores que se quede pillado. 
Cabe destacar que en el último 15-20% de batería estuve con el móvil en el modo de mayor ahorro energético. 
Vengo de una instalación limpia. 

![img_20180403_211200_049](https://user-images.githubusercontent.com/38046575/38270527-f2d85ee0-3783-11e8-88b8-af36ab5b8c29.jpg)
![180403-211436](https://user-images.githubusercontent.com/38046575/38270606-2ee77b78-3784-11e8-925e-28d442841a43.png)
![180403-211445](https://user-images.githubusercontent.com/38046575/38270607-2f0c8efe-3784-11e8-90c1-50ec283fec29.png)

**Comment by ghost** [comment]
Oreo y red 4g no hay mucho que hacer

**Comment by AgustinLorenzo** [comment]
Viendo tus capturas que me mandaste por privado tiene pinta que algun sensor no se apago y provoco que la CPU se quedara activa. Voy a aplicar un fix que me paso @Gabr0 de AOSIP pero vamos creo que adoptare una politica con las aplicaciones que no suspendan los sensores correctamente de cargarmelos en esas aplicaciones.

**Comment by AgustinLorenzo** [comment]
Las siguientes aplicaciones tendran desactivadas el siguiente sensor (Sensor de Movimiento Significativo):

Facebook
GBWhatsapp
Slack
Snapchat
Whatsapp
Whatsapp Plus
YoWhatsapp
Telegram
Telegram Plus
Hike Messenger
GB Instagram

PD: Si, vemos que no mejora despues de esta limpia, seguire bloqueando mas aplicacionesy mas sensores.

**Comment by AgustinLorenzo** [comment]
Fix realizado, aplica en la proxima version.

Link: https://github.com/AgustinLorenzo/android_frameworks_base/commit/56a3eff1b40fa0912db3294557f6fb9b00200f5b

Cierro.
