### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by Schvelt** [AgustinLorenzo/BugTracker#7]
Hoy he recibido un sms mientras miraba una foto desde whatsapp y se ha bloqueado el teléfono, se ha quedado pantalla negra y led encendido. He forzado reinicio y OK.
Estoy en la v5.1
La batería tenía un 80% aproximadamente, perfil ahorro de energía, las apps en standby serían unas 3-4 (telegram, whatsapp,  firefox... ). 
Ha sido al de un rato tras levantarme, después de 6h sin uso intensivo, móvil frío. 
Después de una llamada.

Información aportada por un usuario de telegram. Tengo su @ para aportar si hace falta.

**Comment by AgustinLorenzo** [comment]
Tiene pinta de un fallo aleatorio, o mas bien provocado por el boost que ha echo algo raro, ya ha sido revertido.

Si vuelve a ocurrir dimelo.
