### ISSUE TITLE
Sugerencia: Implementar switch sims 

### ISSUE THREAD

**Issue by Schvelt** [AgustinLorenzo/BugTracker#8]
Tener la posibilidad de "activar/deshabilitar" una o las dos sims cuando se disponga de doble sim. 

(Estoy buscando en qué roms estaba implementado, no me acuerdo, editaré cuando lo encuentre)
AOSIP.

**Comment by AgustinLorenzo** [comment]
Pues...en principio ese codigo esta en la ROM, lo que no se es porque no esta saliendo.

Investigare, para poder activarlo.

**Comment by AgustinLorenzo** [comment]
En la proxima version esta.
