### ISSUE TITLE
Mensaje sobre el dispositivo dando alimentacion a un otg cuando este no está conectado.

### ISSUE THREAD

**Issue by Schvelt** [AgustinLorenzo/BugTracker#9]
Después de conectar un USB por OTG, una vez desconectado este, se queda este mensaje (no tengo comprobado si es absolutamente siempre, me ha pasado a mi y a otro usuario de telegram pero no me he fijado en esto, estaré atenta para especificar exactamente cuando se produce y dar más detalles) y no se quita aunque pongas el móvil a cargar.

![otg](https://user-images.githubusercontent.com/38046575/38501275-de5112e0-3c0c-11e8-9d85-cc3f8928e8ce.jpg)
![otg 2](https://user-images.githubusercontent.com/38046575/38501277-dee472a6-3c0c-11e8-9a27-bc518086295e.jpg)

Falta observar si hay algún caso en que no se produzca este mensaje de error, cuando lo hace exactamente (quitando el OTG de una manera determinada o como).
Falta observar como se quitaba el mensaje (¿Reiniciando? Como digo aunque me ha pasado no me quedé con esos detalles).

**Comment by AgustinLorenzo** [comment]
Corregido en la siguiente version.
